apps:
  alloy:
    enabled: true
    namespace: monitoring
  ca-certs:
    enabled: true
    namespace: cert-manager
  cert-manager:
    enabled: true
    namespace: cert-manager
  dnsserver:
    enabled: true
    extraZones: []
    namespace: addons
    zones: []
      # - rootDomain: "nncorp.home"
      #   ttl: 5m
      #   soa:
      #     rootNameserver: ns.nncorp.home.
      #     maintainer: admin.nncorp.home
      #     serial: 2020010511
      #     peerIntervals:
      #       refresh: 1d
      #       retry: 2h
      #       expiration: 4w
      #     cacheExpiration: 1h
      #   records:
      #     - name: "@"
      #       entries:
      #         - { "class": "IN", "type": "NS", "value": "ns.nncorp.home" }
      #         - { "class": "IN", "type": "A", "value": "172.28.0.2" }
      #         - { "class": "IN", "type": "A", "value": "172.28.0.3" }
      #         - { "class": "IN", "type": "A", "value": "172.28.0.4" }
      #     - name: "ns"
      #       entries:
      #         - { "class": "IN", "type": "CNAME", "value": "@" }
      #     - name: "monitoring"
      #       entries:
      #         - { "class": "IN", "type": "CNAME", "value": "@" }
  docker-registry:
    enabled: true
    namespace: addons
    persistentVolume:
      capacity: 50Gi
  etcd:
    enabled: true
    namespace: kube-system
  grafana:
    enabled: true
    namespace: monitoring
  ingress-controller:
    enabled: true
    namespace: kube-system
    type: traefik
  loki:
    enabled: true
    namespace: monitoring
  trust-manager:
    enabled: true
    namespace: cert-manager
deployment:
  cluster:
    agentArgs: []
    bootstrap:
      dns: true
    dataPath:
      cluster: /mnt
      host: /mnt
    name: docker-k3s
    registry:
      enabled: true
      mirror:
        endpoints: []
    serverArgs: []
    services:
      ingressController: false
      loadBalancer: false
      metricsServer: false
      storageProvisioner: true
    volumeMounts: []
  environment: k3d
global:
  tls:
    ca:
      issuerName: tls-cert-issuer
      secretName: private-root-ca
      selfSigned: false
    cert:
      configMap:
        key: cert.pem
        name: trusted-ca-certs
infra:
  rootDomain: local.cluster.dev
  tls:
    privateCA:
      commonName: mirach.milkyway.com
      countryCode: MW
      emailAddress: mirach@milkyway.com
      expiryDate: "2028-10-19"
      issueDate: "2025-10-19"
      locality: Pegasus Square
      organization: Constellation
      organizationUnit: Star
      postalCode: "209389"
      state: Andromeda
      streetAddress: Mu Andromedae
secrets:
  apps:
    grafana:
      password: admin
      username: admin
  tls:
    ca:
      certificate: null
      privateKey: null
