{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "docker-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - secretName: {{ .Release.Namespace }}-cert
      hosts:
        - {{ default ( include "docker-registry.fullname" . ) .Values.subDomain }}.{{ .Values.rootDomain }}
  rules:
    - host: {{ default ( include "docker-registry.fullname" . ) .Values.subDomain }}.{{ .Values.rootDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "docker-registry.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
{{- end }}
